### ISSUE TITLE
Ubuntu 18.04 package depends on libssl1.0.2 which is not available

### ISSUE THREAD

**Issue by logix2** [BeardOverflow/ts3client-deb#1]
The PPA package for Ubuntu 18.04 depends on libssl1.0.2, which is not available in Ubuntu 18.04, so the ts3client package cannot be installed.

**Comment by BeardOverflow** [comment]
Thanks a lot for reporting this issue.

In the Debian repository, it is libssl1.0.2, but in the Ubuntu repository, it is libssl1.0.0 even being 1.0.2 really. When I built the package, I based on the Debian repository and I did not notice about this conflict. 

I have already fixed with a optional dependency between libssl1.0.0 or libssl1.0.2.

**Comment by logix2** [comment]
Thanks!
